inherit_from: .rubocop_todo.yml

require: rubocop-rspec

inherit_gem:
  bixby: bixby_default.yml

Rails:
  Enabled: true

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Include:
    - '**/Capfile'
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - 'marc_to_solr/translation_maps/*.rb.tmpl'
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/deploy.rb'
    - 'config/initializers/*'
    - 'vendor/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/models/dump_spec.rb'
    - 'marc_to_solr/spec/lib/princeton_marc_spec.rb'
    - 'spec/controllers/availability_controller_spec.rb'
    - 'spec/controllers/patron_controller_spec.rb'
    - 'spec/models/concerns/scsb_partner_updates_spec.rb'
    - 'spec/models/event_spec.rb'
    - 'spec/models/jsonld_record_spec.rb'
    - 'spec/requests/bib_gets_spec.rb'
    - 'spec/requests/course_reserves_spec.rb'
    - 'spec/services/electronic_locations_factory_spec.rb'

Style/BlockDelimiters:
  Exclude:
    - 'spec/models/jsonld_record_spec.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/AccessorMethodName:
  Exclude:
    - 'app/models/concerns/scsb_partner_updates.rb'
    - 'marc_to_solr/lib/princeton_marc.rb'

Lint/HandleExceptions:
  Exclude:
    - 'lib/tasks/spec.rake'
    - 'marc_to_solr/lib/location_extract.rb'
