version: 2
jobs:
  build:
    working_directory: ~/marc_liberation

    # Primary command image where all commands run
    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          PGHOST: 127.0.0.1
          PGUSER: bibdata
          RAILS_ENV: test
      - image: postgres:10.6-alpine
        environment:
          POSTGRES_USER: bibdata
          POSTGRES_DB: marc_liberation_test
          POSTGRES_HOST_AUTH_METHOD: trust

    steps: 
      - checkout
      - run:
          name: Install node@8.17.0 (need right version for `yarn`)
          command: |
            set +e
            touch $BASH_ENV
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.5/install.sh | bash
            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'nvm install v8.17.0' >> $BASH_ENV
            echo 'nvm alias default v8.17.0' >> $BASH_ENV
      - run:
          name: Check current version of node
          command: node -v
      - restore_cache:
          keys:
          - marc_liberation-{{ checksum "Gemfile.lock" }}-2
      - run:
          name: Install phantomjs
          command: sudo apt install phantomjs
      - run: sudo apt-get -y update
      - run: sudo apt-get install -y postgresql-client || true    
      - run: gem install bundler -v '~> 2.0'
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --without development production --jobs 4 --retry 3
      - save_cache:
          key: marc_liberation-{{ checksum "Gemfile.lock" }}-2
          paths:
            - vendor/bundle 
      - run:
          name: Rubocop
          command: bundle exec rubocop

      - run:
          name: Configure location display
          command: cp -v marc_to_solr/translation_maps/location_display.rb.tmpl marc_to_solr/translation_maps/location_display.rb

      - run:
          name: Configure locations
          command: cp -v marc_to_solr/translation_maps/locations.rb.tmpl marc_to_solr/translation_maps/locations.rb

      - run:
          name: Configure holding libraries
          command: cp -v marc_to_solr/translation_maps/holding_library.rb.tmpl marc_to_solr/translation_maps/holding_library.rb

      - run:
          name: Wait for Postgres
          command: dockerize -wait tcp://localhost:5432 -timeout 120s

      - run:
          name: Database setup
          command: bundle exec rake db:setup

      - run:
          name: Rspec
          command: bundle exec rspec spec marc_to_solr/spec
          environment:
            RAILS_ENV: test
            FIGGY_ARK_CACHE_PATH: marc_to_solr/spec/fixtures/figgy_ark_cache
            TRAJECT_CONFIG: marc_to_solr/lib/traject_config.rb
            BIBDATA_ADMIN_NETIDS: admin123

workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build 
      
