default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  database: marc_liberation_dev
  pool: 5

test:
  <<: *default
  database: marc_liberation_test
  pool: 5

production:
  <<: *default
  database: <%= ENV['BIBDATA_DB'] %>
  pool: 20
  username: <%= ENV['BIBDATA_DB_USERNAME'] %>
  password: <%= ENV['BIBDATA_DB_PASSWORD'] %>
  host: <%= ENV['BIBDATA_DB_HOST'] %>
